# Generated by Django 4.1.5 on 2023-02-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
        ('core', '0002_alter_incident_asssigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.profile'),
        ),
    ]
