# Generated by Django 4.1.5 on 2023-02-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incident_reported_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='asssigned_to',
            new_name='assigned_to',
        ),
    ]
