# Generated by Django 4.1.5 on 2023-01-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.jpeg', null=True, upload_to='user/profile'),
        ),
    ]
