# Generated by Django 4.1.5 on 2023-02-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/avatar.jpeg', upload_to='user/profile'),
        ),
    ]
